### PR TITLE
Fixes for search  warnings errors and addressing issue 114

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
renamed this. that comma was causing issues with my local machines git.   Hopefully this doesn't mess everything up.

### CODE REVIEW

**Comment by deepend-tildeclub** [comment]
There now my git should be functioning as intended.    Sorry about all the issues.   I'm not the best at git.

**Comment by RedDragonWebDesign** [comment]
> Sorry about all the issues. I'm not the best at git.

Don't worry, you're not the only one. I hate git :)

**Comment by deepend-tildeclub** [comment]
> > Sorry about all the issues. I'm not the best at git.
> 
> Don't worry, you're not the only one. I hate git. So unintuitive for beginners. Desperately needs a GUI.

I'm ok with no GUI but it could at least be a little less convoluted.   I run tilde.club which mostly centers around the command line. so I'm generally good with that.

**Comment by deepend-tildeclub** [comment]
Is this one also too large?   Or can this one be manageable.

**Comment by RedDragonWebDesign** [comment]
Related #114

**Comment by RedDragonWebDesign** [comment]
Yes, can you split this one too? One patch for the #114 feature, and one patch per page of error fixes. So if you fix all the errors on the search results page, that could be one patch. And if you fix all the errors on the advanced search page, that could be an additional patch.

Adding `public $description` and `public $prefillValues` to Form.php looks suspicious since they are never used. And I can't tell what error they're trying to fix. Splitting into more patches that are clear about what errors the patch is fixing would help review this kind of code.

Thank you for being flexible and responsive to my comments. I appreciate it.

**Comment by deepend-tildeclub** [comment]
> Yes, can you split this one too? One patch for the #114 feature, and one patch per page of error fixes. So if you fix all the errors on the search results page, that could be one patch. And if you fix all the errors on the advanced search page, that could be an additional patch.
> 
> Adding `public $description` and `public $prefillValues` to Form.php looks suspicious since they are never used. And I can't tell what error they're trying to fix. Splitting into more patches that are clear about what errors the patch is fixing would help review this kind of code.
> 
> Thank you for being flexible and responsive to my comments. I appreciate it.

I think its possible that only relevant part of this PR is the 114 portion of it..  Since when I made this one I was still having issues with my git that I didn't realize.  Now things are good so we push the split the 114 portion of it out and throw the rest away.   Hopefully the other PR's I made have a better chance of making it somewhere since I focused on making them as simple and clean as possible.  :)

**Pull request closed without merging**
