### PR TITLE
Fix poll permission issue

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
Fixes poll permission issue.  If you have permission you vote.. if you don't it won't let you.  Fix for issue #52

### CODE REVIEW

**Comment by RedDragonWebDesign** [comment]
For future PRs, if you type `Fix #52` exactly like that in the initial post, it'll automatically link the PR to the issue :)

**Comment by deepend-tildeclub** [comment]
> For future PRs, if you type `Fix #52` exactly like that in the initial post, it'll automatically link the PR to the issue :)

Will do.

**Comment by RedDragonWebDesign** [comment]
It won't let me link this one. Perhaps due to the git branch name. Should try not to put special characters such as = and # in the branch names, if we can avoid it.

**Comment by deepend-tildeclub** [comment]
> It won't let me link this one. Perhaps due to the git branch name. Should try not to put special characters such as = and # in the branch names, if we can avoid it.
yeah I didn't mean to.. mistyped and didn't realize it until i was replying to you the last time.  My bad.

**Pull request closed without merging**
