### PR TITLE
delete btbbcode.php

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
commenting out  preg_replace(    That I'm sure we commented out previously but didn't merge those PR's .. So here it is by itself.

### CODE REVIEW

**Comment by RedDragonWebDesign** [comment]
What page should I test for this one?

**Comment by deepend-tildeclub** [comment]
> commenting out preg_replace( That I'm sure we commented out previously but didn't merge those PR's .. So here it is by itself.

Oh sorry.  

> What page should I test for this one?

              Since this is a syntax error from before you started this patch, I would just comment out $strText by adding `//` to the front of it.

_Originally posted by @RedDragonWebDesign in https://github.com/RedDragonWebDesign/BlueThrust5/pull/88#discussion_r1462359933_


Honestly I'm not aware of any visible errors caused by it.  Its just something you noticed previously when I made changes that we didn't merge due to be needing to separate things out.

**Comment by RedDragonWebDesign** [comment]
Ah yes. Thanks for reminding me.

Taking a closer look at this, I searched the codebase for `btBBCode` (the name of the class/file being modified), and I got zero hits. Therefore I think this file is unused and I'd recommend deleting the entire file instead.

**Comment by deepend-tildeclub** [comment]
> Ah yes. Thanks for reminding me.
> 
> Taking a closer look at this, I searched the codebase for `btBBCode` (the name of the class/file being modified), and I got zero hits. Therefore I think this file is unused and I'd recommend deleting the entire file instead.

yeah lets delete it.  Looks like they integrated this functionality into _functions.php.

**Pull request merged**
