### PR TITLE
init variable in /forum/recent.php

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
Well this really got simplified down.  

Hope this is better.  The other file in the original PR was all changes to style of the code then anything else.

### CODE REVIEW

**Comment by deepend-tildeclub** [comment]
sorry about the .gitignore file.. I didn't mean for it to be added to this one.  But its not my worst PR ever. :S

**Comment by deepend-tildeclub** [comment]
> Haha all good. So this patch has 3 things going on:
> 
> * is adding \n to the end of the file (a Linux thing)
> * is adding to the local gitignore. my idea was for you to add to the global gitignore, but this will work, not worth nitpicking
> * the actual change
> 
> This is mergeable. Will test and merge it in a bit :)

so progress then :)

How should I proceed on that .gitignore.  Since I pushed it accidentally to my master yesterday so If I do all PR's from master then they will all have that .gitignore in them.

**Comment by RedDragonWebDesign** [comment]
https://stackoverflow.com/a/23835912/3480193

These commands should delete any changes in your local repo and make it exactly match the GitHub repo.

```
git fetch --prune origin
git reset --hard origin/master
git clean -f -d
```

Then `git checkout master` to use the master branch as a base. Then `git branch new-branch-name`. etc. etc.

**Comment by RedDragonWebDesign** [comment]
Tested, works. Thanks for the patch!

Before:
image

After:
image

**Pull request merged**
