### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
changed line 255 from || to =.  Not sure if its actually correct doing this but it does fix the blnShowCategoryList error I was having.

### CODE REVIEW

**Comment by deepend-tildeclub** [comment]
In response to issue 77

**Comment by NovemLinguae** [comment]
Related #77

**Comment by RedDragonWebDesign** [comment]
Related #77

**Comment by RedDragonWebDesign** [comment]
This ended up being a red herring and was not the cause of #77. This is just a simple PHP warning triggered by running these PHP 5.6 scripts on PHP 7+.

`if($blnShowCategoryList || true)` is really weird. Doesn't that always just evaluate to true? `false || true` is true, and `true || true` is true. Hmm.

It's not a good habit to use single equals sign in `if` statements. In case you help with this in the future, the best way to handle this warning is to put a `$blnShowCategoryList = 'default value of some kind';` somewhere above the first use of `$blnShowCategoryList` on that page. I'll make the change.

**Pull request closed without merging**
