### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
shows error on main page while logged out.

### CODE REVIEW

**Comment by RedDragonWebDesign** [comment]
I wasn't able to trigger this warning. What's the exact URL for it please?

**Comment by deepend-tildeclub** [comment]
clear your session cookies :)

**Comment by RedDragonWebDesign** [comment]
Step debugging reveals that my `$_SESSION['btUsername']` is equal to `''` not `null`. Hmm.

Are you still able to reproduce this on the latest master branch?

**Comment by deepend-tildeclub** [comment]
> Step debugging reveals that my `$_SESSION['btUsername']` is equal to `''` not `null`. Hmm.
> 
> Are you still able to reproduce this on the latest master branch?

Nope.  Doesn't appear so.   Thanks if you did something else.

**Comment by RedDragonWebDesign** [comment]
Was probably one of our `?? ''`s that we added. Hey, it could have been you too, you never know :)

**Pull request closed without merging**
