### PR TITLE
Fix polls

### PR DESCRIPTION
**Pull request by deepend-tildeclub**
fixes relating to the polls.

### CODE REVIEW

**Comment by RedDragonWebDesign** [comment]
I think you based fix-polls on top of fix-forum instead of master by accident. I'll try to fix it for you using `git rebase master` and some other trickery that I won't try to teach right now because it's really complicated. When I'm done fixing it, please run `git pull` to update your local copy.

**Comment by RedDragonWebDesign** [comment]
Are you testing this code? It has 4 syntax errors. I fixed one of the syntax errors (this duplicate echo statement):

image

But there are still 3 more syntax errors related to braces:

image

**Comment by RedDragonWebDesign** [comment]
I think we should try not to make any changes to code style. Things like spaces, tabs, or whether there's enters after braces. It is cluttering up the diffs, making it hard to see what was actually added or deleted. The code style can be fixed later for the whole repo by automated tools. For example PHP code sniffer and beautifier.

**Comment by deepend-tildeclub** [comment]
> Are you testing this code? It has 4 syntax errors. I fixed one of the syntax errors (this duplicate echo statement):
> 
> image
> But there are still 3 more syntax errors related to braces:
> 
> image

I will take a closer look... Could be possible in the process of separating things I messed something up.    Since I don't know git magic tricks I literally went through each file and copy/pasted to a fresh copy of the repo to add the changes back and is possible I screwed up copying or pasting.   I will watch closer in future.

**Comment by deepend-tildeclub** [comment]
> I think we should try not to make any changes to code style. Things like spaces, tabs, or whether there's enters after braces. It is cluttering up the diffs, making it hard to see what was actually added or deleted. The code style can be fixed later for the whole repo by automated tools. For example PHP code sniffer and beautifier.

So for now I should not try to fix my indentation issues for now?   Just making sure.  So I don't mess this PR up like the last one.  

Thanks again for your help with everything.

**Comment by RedDragonWebDesign** [comment]
> Thanks again for your help with everything.

My pleasure. Sorry that git is such a pain. I've always disliked it. It has a heck of a learning curve. Takes awhile to figure it out.

May also want to switch from Nano to VS Code. I think the indentation stuff might be easier to see with a fancier editor. If you install VS Code, just go File -> Open Folder and open the folder you've been working on. Then all the files in the folder will load up in the left pane, and you can click to open a file, or Ctrl-E to type a file name to open.

> So for now I should not try to fix my indentation issues for now? Just making sure. So I don't mess this PR up like the last one.

We should continue fixing the indentation issues, in the sense that we want to get rid of any changes to indentation compared to the master branch.

Because you used branching I was able to fix some indentation stuff in this PR myself. Yay :)

## We should stop making code style changes ##

What I mean by "I think we should try not to make any changes to code style." is that when you make a new patch / branch / PR, I don't think you should do things like change the tabs, change the location of braces (`}`), and add spaces before and after concatenation (`.`). This is stuff we can do with automated tools later. If you stay active, I'll eventually make some time to do this using an automated tool. This will be consistent, a huge time saver, and much safer (less bug prone) than doing it manually.

For now I think our goal should be patches that have the absolute minimum number of lines changed in order to fix the bug.

A good way to see this is to click on the "Files changed" tab in the GitHub PR.

image

Notice that because so many lines are highlighted green and red to show formatting changes you made, that I cannot easily tell if you added or removed any code? I can't easily tell if this patch is a no-op (has no changes to code behavior), or if it fixed a broken feature, or if it fixed PHP deprecations/notices/warnings/errors.

I think we might need to do another round of patches with just the absolute minimum changes in each patch.

## Use master as the base for each branch ##

The next round of patches should also use master as the base for each branch. I think when you made the branches this time, you kept accidentally using the previous branch / previous patch as the base. If you do `git checkout fix-private-messages` then `git log`, I think you'll see a git log that looks like this:

image

Notice all the commits from other patches that are between the top and the master branch?

When instead it should look like this:

image

We don't want our git patches to be one long chain.

image

We want our git patches to be a bunch of little forks, each fork is a PR.

image

That all make sense?

**Comment by RedDragonWebDesign** [comment]
Let's redo one patch at a time instead of all of them, since that is a lot of work.

- Can you either fix patch #90 or resubmit it from scratch?
- Can it be changed so that it only has a couple lines of code changed when clicking on the "files changed" tab? The lines of code changed should just be to fix whatever is breaking the forum, and not include any changes to tabs, braces, and spacing.
- Can you also write in the patch description exactly what you're fixing? Something like "fix bug where you would click to submit a comment and the website would hang" or "fix PHP error message on page recent.php"? So that when I load up your patch and test it I know what to look for?

Once we do some back and forth on that one and I hit the accept button, then we can move on to additional patches.

Thank you very much :)

**Comment by deepend-tildeclub** [comment]
> > Thanks again for your help with everything.
> 
> My pleasure. Sorry that git is such a pain. I've always disliked it. It has a heck of a learning curve. Takes awhile to figure it out.
> 
> May also want to switch from Nano to VS Code. I think the indentation stuff might be easier to see with a fancier editor. If you install VS Code, just go File -> Open Folder and open the folder you've been working on. Then all the files in the folder will load up in the left pane, and you can click to open a file, or Ctrl-E to type a file name to open.
>

I've been testing out VS Code as well as PHPStorm.  So hopefully as I get used to using either one of those I will get better at this.  
 
> We should continue fixing the indentation issues, in the sense that we want to get rid of any changes to indentation compared to the master branch.
> 
> Because you used branching I was able to fix some indentation stuff in this PR myself. Yay :)

Progress is progress :) 

> ## We should stop making code style changes
> What I mean by "I think we should try not to make any changes to code style." is that when you make a new patch / branch / PR, I don't think you should do things like change the tabs, change the location of braces (`}`), and add spaces before and after concatenation (`.`). This is stuff we can do with automated tools later. If you stay active, I'll eventually make some time to do this using an automated tool. This will be consistent, a huge time saver, and much safer (less bug prone) than doing it manually.
> 

I tried using features in "Phpstorm" to try to sort out the indentation issue and I'm guessing that the settings are not quite what would work properly to match the existing code style.    

> For now I think our goal should be patches that have the absolute minimum number of lines changed in order to fix the bug.
> 
> A good way to see this is to click on the "Files changed" tab in the GitHub PR.

> Accidentally introducing bugs is a huge danger in a repo like this because there are almost zero automated tests.
> 
> I think we might need to do another round of patches with just the absolute minimum changes in each patch.
> 

Like redoing the patches I just sent or next round as in after these PR's are all done. lol

> ## Use master as the base for each branch

I think I understand how that happened wrong.  Instead of going back to the master branch I would still be in another branch and create a branch while still in the non-master branch.   So the chain got worse every time I created another branch.  Again learning curve of using different software.  :(

> The next round of patches should also use master as the base for each branch. I think when you made the branches this time, you kept accidentally using the previous branch / previous patch as the base. If you do `git checkout fix-private-messages` then `git log`, I think you'll see a git log that looks like this:
> 
> We don't want our git patches to be one long chain.
> 
> We want our git patches to be a bunch of little forks, each fork is a PR.
> 
> Git will merge them all back together later when the PRs are accepted.
> 

I think a ton of my issues currently with git is learning a different application which I am using git through.
I was fighting the application every step of the way last night.   

> That all make sense?

I think it makes more sense now.   I'm going to spend some time tonight using PHPStorm or VS Code to do some changes on my own code and see if I can figure it out a bit better.   And then will adjust some stuff on the BlueThrust5 repo. 

Thanks!

**Pull request closed without merging**
